#!/bin/bash

if [[ -z "$1" ]]; then
  echo
  echo "Device not set."
  echo "Usage: build-carbon <device> [user (userdebug) eng]"
  echo
  exit
fi

if [[ -z "$2" ]]; then
  echo
  echo "Build type set to userdebug (default)."
  set -- "$1" "userdebug"
fi

WORK_DIR=~/carbon
OUT_DIR=/android_build_out/carbon

DEVICE=$1
BUILDTYPE=$2

cd $WORK_DIR || exit
source build/envsetup.sh > /dev/null
lunch carbon_"$DEVICE"-userdebug

if [ -d "$OUT_DIR/target/product/$DEVICE" ]; then
  echo
  read -r -p "Want to clean out directory before building? [y/N] " response
  echo
  case "$response" in
    [yY][eE][sS]|[yY])
      make clobber -j8
      echo "Out directory cleaned".
    ;;
    *)
      echo "Making a dirty build."
    ;;
  esac
fi

echo
make carbon -j8
